@startuml

class Jeu {
--
- nouvellePartie():void
- reprendrePartie():void
- verifAnciennePartie():void
- verifGagnant(): void
- sauvegarderPartie():void
- vainqueur(): Joueur
- auSuivant(): Joueur
- verifObligationRemplissage()
+ validationAction()
}

Class Affichage{
- affichage()
- afficherRegles()
- afficherConditionVictoire()
- afficherPoint()
}


class Plateau {
- jetons:Jeton[25]
- privilege:Privilege[]
- sac:Jeton[]
- cartes_nobles:CarteNoble[]
--
+ etatPlateau()
+ remplissagePlateau(): Plateau
+ verificationChoixJetonPlateau()
+ ajouterSac(Jeton)
+ prendreJeton(position_x:int, position_y:int):Jeton
+ prendrePrivilege():Privilege
+ prendreCarteNoble(numero:int):CarteNoble
- verifierSiOrDansChoix()
}



class Joueur {
- IA : bool
- pseudo: string
- nombre_couronnes: int
- points_prestige_total:int
- points_prestige_couleurs:int[5]
- nb_cartes_reservees : int
- cartes_reservees:CarteJoaillerie[]
- cartes_main:CarteJoaillerie[6]
- cartes_noble:CarteNoble[]
- gemmes_bonus:int[5]
- privileges:Privilege[]
- nombre_de_privileges : int
- adversaire : Joueur*
- droit_de_rejouer : bool

+ Joueur(nom : string const)
+ getPointsPrestigeTotal() : int const
+ getPseudo() : string const
+ getNombreCouronnes() : int const
+ getPointsPrestigeCouleurs(index : int) : int const
+ getCarteReservee(index : int) : CarteJoaillerie const
+ getCarteNoble(index : int) : CarteNoble const
+ getGemmesBonus(index : int) : int const
+ getPrivilege(index : int) : Privilege const
+ ajouterCarteJoaillerie(carte : CarteJoaillerie) : void
+ ajouterCarteNoble(carte : const CarteNoble&) : void : void
+ ajouterCarteReservee(carte : const CarteJoaillerie&) : void
+ ajouterPrivilege(privilege : const Privilege&) : void
+ setPointsPrestigeCouleurs(index : int, valeur : int) void
+ setGemmesBonus(index : int, value : int) : void
+ getAdversaire() : Joueur *
+ setAdverxaire(adv : Joueur *) : void
+ hasPrivilege() : bool
+ removePrivilege() : Privilege
+ peutRejouer() : bool
+ resetRejouer(reset : bool) : void
}

class IA {
- difficulte: Difficulte
+ IA(pseudo : const string&, diff : difficulte)
}

enum Difficulte <<enumeration>> {
 facile
 moyen
 difficile
}

class Jeton {
- chemin_vers_image:string
}
class Privilege {
}
class Or {
}
class Gemme {
-couleur: Couleur
}
enum Couleur <<enumeration>> {
 bleu
 vert
 rouge
 blanc
 noir
 rose
 rien
}


class Pioche{
- numero_pioche:int
- cartes_dans_pioche:CarteJoaillerie[]
- cartes_dehors:CarteJoaillerie[]
- max_cartes_revelees:int
+ joueurPrend(numero_carte:int):CarteJoaillerie
+ distribution()
}
class Carte {
- chemin_vers_image:string
- point_prestige:int
- courronnes:int
- pouvoir: Pouvoir
+ actionPouvoir()
- existancePouvoir():Pouvoir
- prendrePrivilege():Privilege
- volerJeton():Jeton
- prendreJeton():Jeton
- rejouer()
- rajouteBonus()
}

class CarteNoble {
-couronne{2,3}: int
}

class CarteJoaillerie {
-niveau[1..3]: int
-couronne[0..2]: int
-pierre: boolean
-type_pierre: Couleur
--
+ getPrix():Gemme[]
}
note left: type_pierre null quand pierre = false


enum Pouvoir <<enumeration>> {
 rien
 nouveau_tour
 bonus_pierre
 pierre_en_plus
 privilege_en_plus
 vol_pierre
}


class Optionnelle {
- depenserPrivilege()
- remplissagePlateau(): Plateau
}

class Obligatoire {
- prendreJeton(): Jeton[]
- reserverCarte():CarteJoaillerie
- acheterCarte():CarteJoaillerie
}


Joueur <|-- IA

Jeu *--- "1" Plateau
Jeu *-- "2" Joueur
Jeu *-- "3" Pioche
Jeu *--"1" Affichage
Jeu *--"0..2" Optionnelle
Jeu *--"0..3" Obligatoire

Plateau "1" --- "0...25" Jeton: possède >
Plateau "1"--"0..3" Privilege: comporte >
Plateau o---"0...4" CarteNoble: contient >
'Plateau "1"-"3" Pioche

Pioche o--"0..67" CarteJoaillerie

Jeton <|-- Or
Jeton <|-- Gemme

Joueur "1" -- "0..3" Privilege: détient >
Joueur "1" --- "0..10" Jeton: possède >
Joueur o--"0..2" CarteNoble

Carte <|-- CarteNoble
Carte <|-- CarteJoaillerie
'(CarteJoaillerie, Pierre) .. AchatCarte






@enduml
